#!/bin/bash
exec > >(tee -i $HOME/dotfiles_install.log)
exec 2>&1
set -x 

dotfiles_root=$(realpath $(dirname $0)/..)

# TODO: Maybe this should be an explicit list?
# Symlink .dotfiles and .dotdirectories to $HOME
for dotfile in $dotfiles_root/.*; do
    if
        # Avoid linking current or parent dir
        [[ $dotfile = "$dotfiles_root/." ]] ||
        [[ $dotfile = "$dotfiles_root/.." ]] ||
        # Avoid linking git administrativia
        [[ $dotfile = "$dotfiles_root/.git" ]] ||
        [[ $dotfile = "$dotfiles_root/.gitignore" ]]
    then
        continue
    fi
    # Link from $HOME to the original here
    ln -sf $dotfile $HOME/$(basename $dotfile)
done

if [ "$CODESPACES" == "true" ]; then
  # missed git branch completion and branch in bash prompt, but didn't
  # want to entirely replace .bashrc
  echo "source $HOME/.codespace-bashrc-tweaks" >> $HOME/.bashrc

  # go seems to need this to install dependencies from github private repos
  echo "machine goproxy.githubapp.com login nobody password $GITHUB_TOKEN" >> $HOME/.netrc
fi
